char menu_principal_re(void);
void gerencia_menu_principal(void);
char ler(void);
// char lers(void);
void cadastrar_re(void);
void editar_re(void);
void excluir_re(void);
void checar_re(void);
void sobre_re(void);
void tipos(void);