char menu_principal_dp(void);
void gerencia_menu_principal_dp(void);
char ler_dp(void);
void cadastrar_dp(void);
void editar_dp(void);
void excluir_dp(void);
void checar_dp(void);
void sobre_dp(void);
void pagar_dp(void);
